#!/bin/bash
# Hook: injects AgentFS context into agent sessions
# Supports: SessionStart, UserPromptSubmit
# Reads the rich agent-context file generated by Constellagent from the AgentFS database.
WS_ID="${AGENT_ORCH_WS_ID:-}"
[ -z "$WS_ID" ] && exit 0

INPUT=$(cat)
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')
[ -z "$CWD" ] && exit 0

REPO="$CWD/.constellagent"
[ ! -d "$REPO" ] && exit 0

# Detect which hook event we're running in
EVENT=$(echo "$INPUT" | jq -r '.hook_event_name // "SessionStart"')

# ── Read context: prefer rich agent-context, fall back to sliding window ──
WS_CONTEXT="$REPO/context/agent-context-${WS_ID}.md"
GLOBAL_CONTEXT="$REPO/context/agent-context.md"
WS_SLIDING="$REPO/context/sliding-window-${WS_ID}.md"
SLIDING="$REPO/context/sliding-window.md"

CONTEXT=""
if [ -n "$WS_ID" ] && [ -f "$WS_CONTEXT" ]; then
  CONTEXT=$(head -c 6000 "$WS_CONTEXT")
elif [ -f "$GLOBAL_CONTEXT" ]; then
  CONTEXT=$(head -c 6000 "$GLOBAL_CONTEXT")
elif [ -n "$WS_ID" ] && [ -f "$WS_SLIDING" ]; then
  CONTEXT=$(head -c 4000 "$WS_SLIDING")
elif [ -f "$SLIDING" ]; then
  CONTEXT=$(head -c 4000 "$SLIDING")
fi

[ -z "$CONTEXT" ] && exit 0

# Tag session start for checkpointing (only on SessionStart)
if [ "$EVENT" = "SessionStart" ] && [ -d "$REPO/.git" ]; then
  git -C "$REPO" -c user.name=Constellagent -c user.email=noreply@constellagent \
    tag "session-start-$(date +%s)" 2>/dev/null
fi

# Build the context prefix based on event type
if [ "$EVENT" = "SessionStart" ]; then
  PREFIX="Previous session context from AgentFS (cross-agent activity):"
else
  PREFIX="Updated cross-agent context from AgentFS:"
fi

jq -n --arg ctx "$CONTEXT" --arg prefix "$PREFIX" --arg event "$EVENT" '{
  hookSpecificOutput: {
    hookEventName: $event,
    additionalContext: ($prefix + "\n" + $ctx)
  }
}'
